#!/bin/bash
# Handler script for curl CLI
# Generated by CLI-to-Skill Converter

COMMAND="curl"

# Build command arguments
ARGS=()

while [[ $# -gt 0 ]]; do
    case $1 in
        --data)
            ARGS+=("--data" "$2")
            shift 2
            ;;
        --fail)
            ARGS+=("--fail" "$2")
            shift 2
            ;;
        --include)
            ARGS+=("--include" "$2")
            shift 2
            ;;
        --O)
            ARGS+=("--O" "$2")
            shift 2
            ;;
        --remote-name)
            ARGS+=("--remote-name" "$2")
            shift 2
            ;;
        --s)
            ARGS+=("--s" "$2")
            shift 2
            ;;
        --silent)
            ARGS+=("--silent" "$2")
            shift 2
            ;;
        --T)
            ARGS+=("--T" "$2")
            shift 2
            ;;
        --upload-file)
            ARGS+=("--upload-file" "$2")
            shift 2
            ;;
        --u)
            ARGS+=("--u" "$2")
            shift 2
            ;;
        --A)
            ARGS+=("--A" "$2")
            shift 2
            ;;
        --user-agent)
            ARGS+=("--user-agent" "$2")
            shift 2
            ;;
        --Agent)
            ARGS+=("--Agent" "$2")
            shift 2
            ;;
        --V)
            ARGS+=("--V" "$2")
            shift 2
            ;;
        --category)
            ARGS+=("--category" "$2")
            shift 2
            ;;
        -*)
            echo "Unknown option: $1"
            exit 1
            ;;
        *)
            ARGS+=("$1")
            shift
            ;;
    esac
done

# Execute command
exec "$COMMAND" "${ARGS[@]}"
